[package]
name = "aidb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.2"
rayon = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.2"